package adslogsreceiver

import (
	"errors"
	"time"

	"github.com/nepionic/otelcol-ads/internal/adsbridge"
	"go.opentelemetry.io/collector/component"
)

// Config holds the configuration for the ADS logs receiver.
type Config struct {
	// TargetNetID is the AMS Net ID of the target TwinCAT system (required).
	// Examples: "192.168.1.1.1.1", "localhost", "127.0.0.1.1.1"
	TargetNetID string `mapstructure:"target_net_id"`

	// RouterAddr is the IP address or hostname of the ADS router.
	// Leave empty when a local TwinCAT router (Windows) is available.
	// Set to the PLC's IP address for direct TCP connections (Linux/BSD).
	RouterAddr string `mapstructure:"router_addr"`

	// RouterPort is the TCP port of the ADS router (default: 48898).
	RouterPort uint16 `mapstructure:"router_port"`

	// PLCPort is the ADS port of the PLC runtime (default: 851 for TC3 runtime 1).
	PLCPort uint16 `mapstructure:"plc_port"`

	// LogRingSymbol is the ADS symbol path of the OTelLogRing variable.
	// Leave empty (default) to auto-discover via the PLC pragma
	// {attribute 'otelcol_role' := 'log_ring'}.
	LogRingSymbol string `mapstructure:"log_ring_symbol"`

	// StatePollingInterval controls how often TwinCAT state is polled for
	// restart detection (default: 2s).
	StatePollingInterval time.Duration `mapstructure:"state_polling_interval"`

	// SubscriptionCycleTime is the ADS notification cycle time used for the
	// write_index subscription (default: 100ms).
	SubscriptionCycleTime time.Duration `mapstructure:"subscription_cycle_time"`

	// ConnectRetryInitialInterval is the first backoff interval after a failed
	// connection attempt (default: 1s).
	ConnectRetryInitialInterval time.Duration `mapstructure:"connect_retry_initial_interval"`

	// ConnectRetryMaxInterval caps the exponential backoff (default: 30s).
	ConnectRetryMaxInterval time.Duration `mapstructure:"connect_retry_max_interval"`

	// SystemLogs configures collector-generated log events for infrastructure-
	// level observability that the PLC application cannot supply itself.
	SystemLogs SystemLogsConfig `mapstructure:"system_logs"`
}

var _ component.Config = (*Config)(nil)

// Validate checks that required fields are set and values are in range.
func (c *Config) Validate() error {
	if c.TargetNetID == "" {
		return errors.New("adslogsreceiver: target_net_id is required")
	}
	if c.SubscriptionCycleTime < 10*time.Millisecond {
		return errors.New("adslogsreceiver: subscription_cycle_time must be at least 10ms")
	}
	return nil
}

// SystemLogsConfig controls collector-generated log events that supplement the
// PLC ring buffer with infrastructure-level observability. These events are
// generated by the collector itself, not by PLC application code, so they
// cover scenarios the PLC cannot observe: state transitions, TCP failures, etc.
type SystemLogsConfig struct {
	// Enabled is the master switch for all system log emission (default: true).
	// Set to false to disable all system logs without changing other fields.
	Enabled bool `mapstructure:"enabled"`

	// PLCStateChanges emits a log record on each TwinCAT ADS state transition,
	// e.g. Run → Stop, Config → Run, or when the initial state is first read.
	// Useful for correlating application failures with PLC lifecycle events.
	// Default: true.
	PLCStateChanges bool `mapstructure:"plc_state_changes"`

	// ConnectionEvents emits log records when the collector establishes a
	// connection, loses the connection, or reconnects after a TwinCAT restart.
	// Default: true.
	ConnectionEvents bool `mapstructure:"connection_events"`

	// RingOverflows emits a warning log record when the PLC writes entries to
	// the ring faster than the collector drains them, causing data loss.
	// Default: true.
	RingOverflows bool `mapstructure:"ring_overflows"`
}

// toBridgeConfig converts the receiver Config to the shared adsbridge.Config.
func (c *Config) toBridgeConfig() adsbridge.Config {
	return adsbridge.Config{
		TargetNetID:          c.TargetNetID,
		RouterAddr:           c.RouterAddr,
		RouterPort:           c.RouterPort,
		PLCPort:              c.PLCPort,
		StatePollingInterval: c.StatePollingInterval,
	}
}
